# Generated by Django 5.1.2 on 2024-11-07 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_contact_book'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact_book',
            new_name='ContactBook',
        ),
    ]
